baseurl = "https://9op.github.io/"
languageCode = "en-us"
title = "Martin"
theme = "default"
paginate = 5
copyright = "Copyright Â© 2021 - Martin Guyard"


[markup]
  [markup.highlight]
    lineNos = true
    style = "monokai" # "solarized-dark"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 4
    ordered = false

[params] 
  contentTypeName = "post"
  defaultTheme = "light" # dark / light
  showMenuItems = 3 # elements before submenu trigger
  sources = "<a href='https://github.com/9op/9op.github.io'> sources </a>"

[languages]
    [languages.en.params.logo]
      logoText = "/home"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archives"
        url = "/archive"